version: "3"

services:
  pxe:
    build: ./
    image: arnio/pxe:latest
    restart: always
    environment:
      DHCP_NETBIOS_NAME_SERVERS: ${DHCP_NETBIOS_NAME_SERVERS:-phenix}
      DHCP_RANGE: ${DHCP_RANGE:-192.168.1.40 192.168.1.60}
      DHCP_SUBNET1: ${DHCP_SUBNET1:-192.168.1.0}
      DOMAIN: ${DOMAIN:-example.com}
      DNS_SERVER: ${DNS_SERVERS:-8.8.8.8}
      DNS_UPSTREAM: ${DNS_UPSTREAM:-8.8.8.8}
      NTP_SERVER: ${NTP_SERVERS:-0.pool.ntp.org}
      PORT_DNSMASQ_DNS: ${PORT_DNSMASQ_DNS:-5353}
      SUBNET1_GATEWAY: ${SUBNET1_GATEWAY:-192.168.1.1}
      SUBNET1_INTERFACE: ${SUBNET1_INTERFACE:-enp0s3}
      TZ: ${TZ:-UTC}
    ports:
    - ${PORT_DNSMASQ_DNS:-5353}:53/udp
    - 67:67/udp
    - 69:69/udp
    volumes:
    - ./pxelinux:/tftpboot/pxelinux:ro
    - ./etc/dhcpd.d:/etc/dhcpd.d/local:ro
    - ./etc/dnsmasq.d:/etc/dnsmasq.d/local:ro
    - leases:/var/lib/misc
    network_mode: host
    cap_add:
    - NET_ADMIN

volumes:
  leases: